name: Execute notebook

on:
  workflow_dispatch:
  push:
    paths:
      - '**.ipynb'
      - '**/**.ipynb'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Jupyter Notebooks to PDF
      uses: MohamedElashri/Jupyter-to-PDF@v1.3
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
